#!/bin/sh

. ./image-env.sh

docker tag $IMAGE_NAME:$IMAGE_VERSION-$BUILD_NUM $REGISTRY/$REGISTRY_USER_ID/$IMAGE_NAME:$IMAGE_VERSION-$BUILD_NUM
docker push $REGISTRY/$REGISTRY_USER_ID/$IMAGE_NAME:$IMAGE_VERSION-$BUILD_NUM